version: '3'


services:
  minio:
    image: minio/minio
    volumes:
      - ./export:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio_handler
      MINIO_SECRET_KEY: dzR1301qxc
    command: server /export

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
  web:
    image: tp_enzo:latest
    ports:
      - 8080:80
    links:
     - db
     - minio
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
